### ISSUE TITLE
go.mod toolchain報錯

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#121]
我本地直接`go run ./main.go`的時候會報錯，但是go.mod裡面toolchain那行刪掉就好了，其他看起來正常。
![image](https://github.com/user-attachments/assets/61102847-2fbb-404d-a21b-a69f1c5479ac)
https://github.com/NYCUarchery/archeryWebsite/blob/ccaba1eefc9f8644e9aac9dfcf500864da2ed432/backend/go.mod#L5

**Comment by Mushroom-MSL1L** [comment]
Golang 1.21的向下兼容新玩具

降到1.20就好

**Comment by Mushroom-MSL1L** [comment]
如果需要用到1.20以後的golang 語法的module在用吧
目前先降到1.20，先關這個issue
