### ISSUE TITLE
後端yaml有點髒髒的

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#123]
後端的config裡面的yaml檔案有點髒髒的。
https://github.com/NYCUarchery/archeryWebsite/blob/a6f0200f430c2e676329f83a0183bb05a2ede55e/backend/config/db.yaml.sample#L1-L11

這種形式的比較乾淨，但somehow有兩個。
https://github.com/NYCUarchery/archeryWebsite/blob/a6f0200f430c2e676329f83a0183bb05a2ede55e/backend/config/db%20copy.yaml#L1-L6

命名可以用db.example.yaml

**Comment by Mushroom-MSL1L** [comment]
之後改
不知道是什麼時候多複製的跑上去了😢

**Comment by Mushroom-MSL1L** [comment]
#142

**Comment by Otmeal** [comment]
Close #142
