### ISSUE TITLE
完善swagger

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#133]
據 @Mushroom-MSL1L 所說，目前swagger還不是很完整，希望可以把這一部份補全，這樣在未來維護上面也會比較方便，大家也不用再用postman去戳API。

**Comment by Mushroom-MSL1L** [comment]
@Bennybenny124 昕叡好棒

**Comment by Otmeal** [comment]
ㄟ，我們有些model的relation有點多層， @Mushroom-MSL1L 可能要幫忙一下。

**Comment by Mushroom-MSL1L** [comment]
之後會用structure繼承來簡化這部分，然後主要還是交給昕叡處理。該交接的都交接完了。

**Comment by Otmeal** [comment]
qualification甚至沒有struct。
/api/qualification/lanes/players/:id是錯的。swagger前面掛了一個data
https://github.com/NYCUarchery/archeryWebsite/blob/647836af30fd3c056cf918c0013cbe0887ff9eb1/backend/docs/swagger.yaml#L2639

**Comment by Otmeal** [comment]
![image](https://github.com/user-attachments/assets/5292528e-0de1-4f37-ad38-b2e78ab3fb6b)
這個東西被自己一個人包在"api"底下

**Comment by Mushroom-MSL1L** [comment]
> ![image](https://private-user-images.githubusercontent.com/87589405/363967282-5292528e-0de1-4f37-ad38-b2e78ab3fb6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjQ1MDUsIm5iZiI6MTcyNTM2NDIwNSwicGF0aCI6Ii84NzU4OTQwNS8zNjM5NjcyODItNTI5MjUyOGUtMGRlMS00ZjM3LWFkMzgtYjJlNzhhYjNmYjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDExNTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZjkwODg1M2IxMzU5ODJiNTQ5NmVjMmIzNDY5NjM2OTNjMTQwODFhYTY4NzJhYWRmYmRhMGQ5ZTA1MmY5NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fCOitd8CEL_ZfhDdaPKI_lDvUs6wiYni5sMCTlG417A) 這個東西被自己一個人包在"api"底下

#142 裡面修好了

**Comment by Otmeal** [comment]
> > ![image](https://private-user-images.githubusercontent.com/87589405/363967282-5292528e-0de1-4f37-ad38-b2e78ab3fb6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjQ1MDUsIm5iZiI6MTcyNTM2NDIwNSwicGF0aCI6Ii84NzU4OTQwNS8zNjM5NjcyODItNTI5MjUyOGUtMGRlMS00ZjM3LWFkMzgtYjJlNzhhYjNmYjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDExNTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZjkwODg1M2IxMzU5ODJiNTQ5NmVjMmIzNDY5NjM2OTNjMTQwODFhYTY4NzJhYWRmYmRhMGQ5ZTA1MmY5NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fCOitd8CEL_ZfhDdaPKI_lDvUs6wiYni5sMCTlG417A) 這個東西被自己一個人包在"api"底下
> 
> #142 裡面修好了

下次一個branch修一樣東西就好。

**Comment by Otmeal** [comment]
![image](https://github.com/user-attachments/assets/1ef59582-1598-408a-bb9b-fd48fba0c381)
這條是錯的，group_id應該要用一個body給。

**Comment by Otmeal** [comment]
![image](https://github.com/user-attachments/assets/a4597cb4-5764-46e1-a246-14665efef464)
unassiged應該是小寫。

**Comment by Otmeal** [comment]
![image](https://github.com/user-attachments/assets/e82f953a-5581-4ae3-b29f-6bdfa047faa4)
這個原來沒有定義body。

**Comment by Otmeal** [comment]
![image](https://github.com/user-attachments/assets/d9d049e0-77a0-400c-88f5-8426282206a3)
這條API應該是`/api/player/lane/{id}`，然後也漏body。

**Comment by Otmeal** [comment]
![image](https://github.com/user-attachments/assets/79b300a5-b5a5-40cb-867f-d7315864639e)
這個也是錯的，應該是`/competition/groups/quaeli/${id}`

**Comment by Otmeal** [comment]
![image](https://github.com/user-attachments/assets/bf287ff8-88d3-4a3a-b190-822f7370f77e)
這裡的命名有一點誤導性，看起來像是撈全部的lane出來。

**Comment by Mushroom-MSL1L** [comment]
剛好都是@Bennybenny124 要改的

**Comment by Otmeal** [comment]
![image](https://github.com/user-attachments/assets/c98cec05-6499-4985-a9e6-99062a4b85d5)
這條plus前面少一個斜線。

**Comment by Otmeal** [comment]
![image](https://github.com/user-attachments/assets/08ae36f2-b266-461d-aae8-a607d714fa9d)
少body。

**Comment by Mushroom-MSL1L** [comment]
> ![image](https://private-user-images.githubusercontent.com/87589405/366066793-08ae36f2-b266-461d-aae8-a607d714fa9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjQwODAsIm5iZiI6MTcyNjAyMzc4MCwicGF0aCI6Ii84NzU4OTQwNS8zNjYwNjY3OTMtMDhhZTM2ZjItYjI2Ni00NjFkLWFhZTgtYTYwN2Q3MTRmYTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAzMDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNDNjNjdiYTgyNzM2MWRjYjBlNzkxZGNmZjJiMmI5ZWI2MWQyZmM2MmQyZjE0YmIzOGY0MTFjMGNhYzRiNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PUgtTtGUf7lYP-ofqWXBXr0gAbTAEKhxHB7S-EROKmE) 少body。

<img width="682" alt="image" src="https://github.com/user-attachments/assets/497cf528-509b-42be-a288-fb441857cc75">

#146 已解決

**Comment by Mushroom-MSL1L** [comment]
@Otmeal 已解決的你確認之後把comment 刪掉吧
東西太多了

**Comment by Otmeal** [comment]
9/14:
@Bennybenny124 進度回報一下。

**Comment by Otmeal** [comment]
![image](https://github.com/user-attachments/assets/66b2bb50-ff4f-48a2-aa06-525cda7f3bab)
這個的route不對。

**Comment by Mushroom-MSL1L** [comment]
截至這個comment為止，前面的問題都在swag-master解決了
