### ISSUE TITLE
total score更好的處理方法

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#138]
因為之前有遇到total score跟實際箭的分數有脫鉤的情況。目前的處理方式是管理員戳一個API才會觸發各個total score的重新計算，目前想到兩個做法：
- DB不存total，每次都用算的再加到json裡面給前端。
- 只要有改到箭的分數就觸發total score重新加總（以前是在當下的值上做加減）。

**Comment by Mushroom-MSL1L** [comment]
如果時間不夠我傾向後者
這樣我就不用改其他函式了。
不管選哪個都是有seeder之後會比較好試。

**Comment by Otmeal** [comment]
Todo:
- 改單支的的箭的API改成重算total_score。

**Comment by Mushroom-MSL1L** [comment]
9/14
之後開新的branch整合total score features ：
1. 有改箭值的api，就refresh相關的total score。
2. 單一改total scores, just in case.
3. 一個api refresh 整個qualification or elimination 的 totals scores。
