### ISSUE TITLE
getCompetitionCurrentDetail有query要求

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#139]
![image](https://github.com/user-attachments/assets/47ba6be3-52ae-445f-aac2-bf5a2137d81b)
大部分的get好像都沒有query那項，可能要找找差在哪裡。

**Comment by Otmeal** [comment]
@Mushroom-MSL1L 等等不好了，他swagger寫說會回傳string

**Comment by Otmeal** [comment]
9/8
- query是swagger自己生的，目前要手動修掉，或是考慮照著有query的pattern寫。

**Comment by Mushroom-MSL1L** [comment]
看起來沒問題，沒需要特別注意的，等benny完成吧

**Comment by Otmeal** [comment]
9/21
等均祐完成吧。

**Comment by Otmeal** [comment]
Fixed by #169
