### ISSUE TITLE
swagger的route髒髒的

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#140]
整個有設了一個`basePath: /api/`

但是有些path前面又掛了一個`/api/`：
https://github.com/NYCUarchery/archeryWebsite/blob/647836af30fd3c056cf918c0013cbe0887ff9eb1/backend/docs/swagger.json#L18
有些沒有掛：
https://github.com/NYCUarchery/archeryWebsite/blob/647836af30fd3c056cf918c0013cbe0887ff9eb1/backend/docs/swagger.json#L3855
還有中間多了反斜線的：
https://github.com/NYCUarchery/archeryWebsite/blob/647836af30fd3c056cf918c0013cbe0887ff9eb1/backend/docs/swagger.json#L58

**Comment by Otmeal** [comment]
暫時解決，我手動改了一下前端生出來的class。

**Comment by Mushroom-MSL1L** [comment]
不要照swag的
照postman 你測試沒問題的

**Comment by Mushroom-MSL1L** [comment]
#133

**Comment by Otmeal** [comment]
Duplicated #133
