### ISSUE TITLE
swagger route吃的parameter schema有些沒寫好

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#141]
這裡是有寫好的，3047行有指定參數的schema是`#/definitions/endpoint.AccountInfo`。
https://github.com/NYCUarchery/archeryWebsite/blob/647836af30fd3c056cf918c0013cbe0887ff9eb1/backend/docs/swagger.yaml#L3031-L3047

但好像很多都只有給一個string：
https://github.com/NYCUarchery/archeryWebsite/blob/647836af30fd3c056cf918c0013cbe0887ff9eb1/backend/docs/swagger.yaml#L245-L258

這個部份因為IDE可以看swagger的資料直接給我提示這個route需要什麼東西，所以如果寫好的話我在接API會快很多。

**Comment by Mushroom-MSL1L** [comment]
不是蟲子
先看postman
你看到的是趕鴨子上架的東東

**Comment by Otmeal** [comment]
合併 #140 VScode會跟我說我的Request body要是個string（一般前端這邊也是直接寫成一個struct不需要另行轉換） & 戳API的Object 會去戳 api/api/competition 🥺

**Comment by Otmeal** [comment]
目前生出一個workaround

**Comment by Mushroom-MSL1L** [comment]
#133

**Comment by Otmeal** [comment]
Duplicated #133
