### ISSUE TITLE
Handle promotion

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#151]
promotion：下面組別的人對抗賽的時候要往上打，需要幫他們生一個新的player到新的組別。

**Comment by Mushroom-MSL1L** [comment]
請解釋

**Comment by Otmeal** [comment]
9/20

- [ ] - 後端有DummyPlayer，但是總分會變成-1，但是會影響到player set的總分，這個還要改成0。
- [ ] - 前端還沒handle。

**Comment by Otmeal** [comment]
佳穎說先不用。

**Comment by Otmeal** [comment]
佳穎說先不用。
