### ISSUE TITLE
broken swagger thread

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#171]
![image](https://github.com/user-attachments/assets/31cfba30-65ec-4240-89f8-07092efd5737)
這個playerid看起來是多的。
然後id應該是number會比較統一。

**Comment by Otmeal** [comment]
這裡api吐出來的是一個DatabaseParticipant array，但是swagger只有寫DatabaseParticipant。。
![image](https://github.com/user-attachments/assets/c6d09a20-6b97-4b07-ab09-a62c2a230402)

**Comment by Mushroom-MSL1L** [comment]
#186

**Comment by Mushroom-MSL1L** [comment]
close with #186
