### ISSUE TITLE
Post Participant can't read role.

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#51]
如果我這樣post participants，他讀不到role。
![image](https://github.com/NYCUarchery/archeryWebsite/assets/87589405/b21f09d3-e787-4636-ba29-d76d8c2a3b80)

![image](https://github.com/NYCUarchery/archeryWebsite/assets/87589405/ab6d9dfd-5268-4d4d-9341-a71ddedafb45)

之前如果是直接戳DB建的是可以的。

**Comment by JasonTuTW** [comment]
他目前在profile-backend上面QQ

**Comment by Otmeal** [comment]
看起來解決了。
