### ISSUE TITLE
The creation of host participant when posting a competition.

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#74]
我重組比賽創建頁面的時候遇到了一些問題，
現在我讓使用者可以填寫主辦人的ID，預設是他自己的ID。

有一些問題：

1. post participant需要登入才可以運作（不過好像沒有限制只能用自己的userID post，好像哪裡怪怪的），要把這個功能取消嗎？
2. post paticipant不能指定status，預設都是pending，所以要在創建比賽後創建主持人的管理員participant的話，要post然後再把status put成 "approved"。
3. post competition 也許可以在同一個API內把 2.想完成的事情完成？

如過很Confusing的話可以敲我，我可能有漏掉一些細節 ;(

**Comment by Mushroom-MSL1L** [comment]
回覆
1. 蛤
2. 可以，我來弄，和你討論細節。
3. 可以，合起來。
