### ISSUE TITLE
由後端計算的總分有機會出錯

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#89]
總分改由前端計算。

**Comment by Otmeal** [comment]
目前分數榜的分數由前端計算， @Mushroom-MSL1L先做了一個put total score來讓排名可以控制，之後要改個算法，有個API可以計算總分並排名。

**Comment by Mushroom-MSL1L** [comment]
在Scoring and date bug fix #99 做了新api去重新計算總分，該api功能與原本的rank排名api是互相獨立的。
